"""
The purpose of this class is to take in a transaction vector (as generated by a gene3agent from the JHG engine)
as well as a current optiosn matrix from SC voting allocations, and then calculate the distances between the
allocation and all possible votes, and then return the index of the closest possible vote. in this way, we can create
a way for these gene3agents to vote using a transaction vector.
"""
import numpy as np


class transVecTranslator:
    def __init__(self):
        pass # not sure what to put here yhet

    def translateVecToIndex(self, transVec, currentOptionsMatrix):
        total_distances = []
        for curr_index in currentOptionsMatrix:
            curr_column = [row[curr_index] for row in transVec]
            total_distances.append(np.linalg.norm(np.array(transVec) - np.array(curr_column)))
        new_distances = [abs(distance) for distance in total_distances] # get the abs value
        index_to_return = new_distances.index(min(new_distances)) # ge the min of the abs
        print("this was the distance between allocation and vote ", total_distances[index_to_return]) # want to see pos or neg for fun
        return index_to_return # the vote that was the closest.