"""
The purpose of this class is to take in a transaction vector (as generated by a gene3agent from the JHG engine)
as well as a current optiosn matrix from SC voting allocations, and then calculate the distances between the
allocation and all possible votes, and then return the index of the closest possible vote. in this way, we can create
a way for these gene3agents to vote using a transaction vector.
"""
import numpy as np
import copy

# not sure why we have this in a separate file but here we are
def translateVecToIndex(transVec, currentOptionsMatrix, enforce_majority):
    total_distances = []

    # abstention is still an option, but it just won't pass.
    new_options_matrix = copy.deepcopy(currentOptionsMatrix)
    new_options_matrix = [[0] + row for row in new_options_matrix]  # add a 0 column right off the bat.
    transposed_matrix = list(zip(*new_options_matrix))  # Now each item is a column
    transVec = np.array(transVec)
    for column in transposed_matrix:
        if transVec.shape[0] != np.array(column).shape[0]:
            print("uh oh")
        distance = np.linalg.norm(
            np.array(transVec) - np.array(column))  # remember that euclidian distances are always positive
        total_distances.append(distance)
    index_to_return = total_distances.index(min(total_distances))  # ge the min of the abs
    # print("these are the total distances ", total_distances)
    # print("this was the distance between allocation and vote ", total_distances[index_to_return]) # want to see pos or neg for fun
    return index_to_return - 1  # the vote that was the closest. (rememnber, 0 shoudl be represented as -1, off by one erorr here.

    # else:
    #     transposed_matrix = list(zip(*currentOptionsMatrix))  # Now each item is a column
    #     for column in transposed_matrix:
    #         distance = np.linalg.norm(
    #             np.array(transVec) - np.array(column))  # remember that euclidian distances are always positive
    #         total_distances.append(distance)
    #     index_to_return = total_distances.index(min(total_distances))  # ge the min of the abs
    #     # print("this was the distance between allocation and vote ", total_distances[index_to_return]) # want to see pos or neg for fun
    #     return index_to_return  # the vote that was the closest. (rememnber, 0 shoudl be represented as -1, off by one erorr here.



# legacy version that creates and maintains a possible abstention column. we are getting rid of this.
# # not sure why we have this in a separate file but here we are
# def translateVecToIndex(transVec, currentOptionsMatrix):
#     # we also have to include an abstain option.
#     new_options_matrix = copy.deepcopy(currentOptionsMatrix)
#     new_options_matrix = [[0] + row for row in new_options_matrix] # add a 0 column right off the bat.
#     total_distances = []
#
#     transposed_matrix = list(zip(*new_options_matrix))  # Now each item is a column
#
#     for column in transposed_matrix:
#         distance = np.linalg.norm(np.array(transVec) - np.array(column)) # remember that euclidian distances are always positive
#         total_distances.append(distance)
#     index_to_return = total_distances.index(min(total_distances)) # ge the min of the abs
#     #print("this was the distance between allocation and vote ", total_distances[index_to_return]) # want to see pos or neg for fun
#     return index_to_return-1 # the vote that was the closest. (rememnber, 0 shoudl be represented as -1, off by one erorr here.